volumes:
  rabbitmq_data:

services: 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    # hostname is important for RabbitMQ volumes persistence
    # https://github.com/docker-library/rabbitmq/issues/392
    hostname: rabbitmq
    ports:
      # Standard AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      DEFAULT_USER: "guest"
      DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
